title = "Nexus Food Delivery"
baseURL = "https://nexusfooddelivery.com/"
languageCode = "en-us"
theme = "airspace-hugo"
copyright = "2018 Nexus Heights"

[menu]

  [[menu.header]]
    weight = 2
    name = "Partners"
    url = "/partners"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "https://blog.nexusfooddelivery.com/"
  [[menu.header]]
    weight = 4
    name = "Partners"
    url = "/partners"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "Contact Us"
    url = "/contact"
  [[menu.footer]]
    weight = 2
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "Blog"
    url = "https://blog.nexusfooddelivery.com/"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"


  [params.slider]
    enable = true
    title = "Nexus Food Delivery"
    subtitle = "A revolutionary new food delivery service serving the Cookeville, TN area."

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Nexus Food Delivery declassified."
    paragraph = "Nexus Food Delivery is a new delivery service coming to the Cookeville, TN area. With custom built apps engineered for speed and reliability and lower fees than the competitors, we hope to provide a level of service to the people of Cookeville that is simply unparalleled."

  [params.feature]
    enable = true
    title = "It's Good to be a Driver"
    italic = "Read about the benefits."
    content = "Drivers get half of the delivery fee. And a percentage of the order cost. And 100% of the tips they receive.\n\nSimply put, it's good to be a Nexus Food Delivery driver. If you're wanting to join the Nexus Food Delivery family, please click the button below to send us an email with your name and phone number and we'll get back to you ASAP."
    [params.feature.button]
      caption = "Inquire About Driving"
      url = "mailto:nexusheights@gmail.com"

  [params.call]
    enable = true
    title = "Arriving July 2018"
    paragraph = "Nexus Food Delivery will be arriving on the App Store® and the web later this month. Please keep an eye on our blog for more information."

  [params.contact]
    enable = false
    title = "Get Ahold of Us"
    subtitle = "Questions? Complaints? Comments? We'd love to hear from you."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Alternative Contact Methods"
      address = "N/A"
      email = "nexusheights@gmail.com"
      phone = "N/A"
    [[params.contact.social]]
      url = "http://instagram.com/nexusfooddelivery"
      icon = "fa-instagram"
      [[params.contact.social]]
        url = "http://twitter.com/Nexus-FD"
        icon = "fa-twitter"
        [[params.contact.social]]
          url = "http://facebook.com/nexusfooddelivery"
          icon = "fa-facebook"
